---
- name: smart management setup - quickstart ex2
  hosts: localhost
  gather_facts: no
  
  environment:
       CONTROLLER_HOST: "{{ controller }}"
       CONTROLLER_USERNAME: "{{ user }}"
       CONTROLLER_PASSWORD: "{{ pass }}"
       CONTROLLER_VERIFY_SSL: False

  tasks:

    - name: Create OpenSCAP Configure Job
      ansible.controller.job_template:
        name: "OpenSCAP Configure"
        tower_host: "{{ controller }}"
        tower_username: "{{ user }}"
        tower_password: "{{ pass }}"
        job_type: "run"
        organization: "Default"
        inventory: "RHEL7 Development"
        project: "Automated Management"
        execution_environment: "smart_mgmt workshop execution environment"
        playbook: "configure_openscap.yml"
        credentials:
          - "Workshop Credential"
          - "Satellite Credential"
        extra_vars:
          HOSTS: all
          Policy_scan:
            - STIG_Compliance
        state: "present"
      register: job
      tags: [ never, openscap_configure]

    - name: debug
      debug:
        var: job
      tags: [ never, openscap_configure ]

    - name: Wait for job OpenSCAP_Configure Template
      ansible.builtin.pause:
        minutes: 1
      tags: [ never, openscap_configure ]
      when: job.changed


    - name: Launch Job - OpenSCAP_Configure
      ansible.controller.job_launch:
        tower_host: "{{ controller }}"
        tower_username: "{{ user }}"
        tower_password: "{{ pass }}"
        name: "OpenSCAP Configure"
      register: job
      tags: [ never, openscap_configure ]

    - name: Wait for job OpenSCAP_Configure
      ansible.controller.job_wait:
        job_id: "{{ job.id }}"
        tower_host: "{{ controller }}"
        tower_username: "{{ user }}"
        tower_password: "{{ pass }}"
        timeout: 800
      tags: [ never, openscap_configure ]

