---
- name: smart management setup - quickstart ex1
  hosts: localhost
  gather_facts: no
  collections:
    - awx.awx
  
  environment:
    #CONTROLLER_HOST: "{{ controller }}"
    #CONTROLLER_USERNAME: "{{ user }}"
    #CONTROLLER_PASSWORD: "{{ pass }}"
    #CONTROLLER_VERIFY_SSL: False

  tasks:

    - name: Create OpenSCAP Configure Job
      awx.awx.job_template:
        name: "OpenSCAP Configure"
        job_type: "run"
        organization: "Default"
        inventory: "RHEL7 Development"
        project: "Automated Management"
        execution_environment: "smart_mgmt workshop execution environment"
        playbook: "configure_openscap.yml"
        credentials:
          - "Workshop Credential"
          - "Satellite Credential"
        extra_vars:
          HOSTS: all
          Policy_scan:
            - STIG_Compliance
        state: "present"
      register: job

    - name: debug
      debug:
        var: job

    - name: Wait for job OpenSCAP_Configure Template
      ansible.builtin.pause:
        minutes: 1
      when: job.changed


    - name: Launch Job - OpenSCAP_Configure
      awx.awx.job_launch:
        name: "OpenSCAP Configure"
      register: job

    - name: Wait for job OpenSCAP_Configure
      awx.awx.job_wait:
        job_id: "{{ job.id }}"
        timeout: 800
