- name: Create ServiceNow templates in AAP
  hosts: localhost
  gather_facts: false
  collections:
  - ansible.controller
  vars:

  environment:
    CONTROLLER_HOST: "{{ controller }}"
    CONTROLLER_USERNAME: "{{ user }}"
    CONTROLLER_PASSWORD: "{{ pass }}"
    CONTROLLER_VERIFY_SSL: False

  tasks:

  - name: 'Create Template to automate Exercise 0 (Setup)'
    ansible.controller.job_template:
      name: "Run Satellite Exercise 0"
      job_type: "run"
      organization: "Default"
      inventory: "Workshop Inventory"
      project: "Ansible and Satellite Exercise Automation"
      execution_environment: "auto_satellite controller iac execution environment"
      playbook: "automate_sm_setup_ex0.yml"
      credentials:
        #- "{{ Controller Credential }}"
        - "Controller Credential"
      extra_vars:
      state: "present"
    register: job

  - name: Print job output
    ansible.builtin.debug:
      var: job
      verbosity: 2

  - name: 'Create Template to automate Exercise 1'
    ansible.controller.job_template:
      name: "Run Satellite Exercise 1"
      job_type: "run"
      organization: "Default"
      inventory: "Workshop Inventory"
      project: "Ansible and Satellite Exercise Automation"
      execution_environment: "auto_satellite controller iac execution environment"
      playbook: "automate_sm_setup_ex1.yml"
      credentials:
        - "Controller Credential"
        #- "{{ Controller Credential }}"
      extra_vars:
      state: "present"
    register: job

  - name: Print job output
    ansible.builtin.debug:
      var: job
      verbosity: 2

  - name: 'Create Template to automate Exercise 2'
    ansible.controller.job_template:
      name: "Run Satellite Exercise 2"
      job_type: "run"
      organization: "Default"
      inventory: "Workshop Inventory"
      project: "Ansible and Satellite Exercise Automation"
      execution_environment: "auto_satellite controller iac execution environment"
      playbook: "automate_sm_setup_ex2.yml"
      credentials:
        - "Controller Credential"
        #- "{{ Controller Credential }}"
      extra_vars:
      state: "present"
    register: job

  - name: Print job output
    ansible.builtin.debug:
      var: job
      verbosity: 2

  - name: 'Create Template to automate Exercise 3'
    ansible.controller.job_template:
      name: "Run Satellite Exercise 3"
      job_type: "run"
      organization: "Default"
      inventory: "Workshop Inventory"
      project: "Ansible and Satellite Exercise Automation"
      execution_environment: "auto_satellite controller iac execution environment"
      playbook: "automate_sm_setup_ex3.yml"
      credentials:
        - "Controller Credential"
        #- "{{ Controller Credential }}"
      extra_vars:
      state: "present"
    register: job

  - name: Print job output
    ansible.builtin.debug:
      var: job
      verbosity: 2
